In [1]:
%matplotlib inline
#%qtconsole

In [2]:
import numpy as np
import scipy.stats
from statsmodels.api import GLM, families
from regularized_glm.core import penalized_IRLS

n_samples = 1000
response = scipy.stats.norm(loc=5).rvs(n_samples)
design_matrix = np.ones_like(response)

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/miniconda3/envs/regularized_glm/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


array([5.02726476])

array([5.02726476])

True

array([[0.0009858]])

array([[0.0009858]])

2824.571550975896

2824.571550975896

0.9857968154876611

0.985796815487661

In [3]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

array([5.05758212, 4.98939739])

array([5.05758212, 4.98939739])

True

array([[ 0.00197627, -0.00197627],
       [-0.00197627,  0.00395255]])

array([[ 0.00197627, -0.00197627],
       [-0.00197627,  0.00395255]])

2827.941001606057

2827.941001606057

0.9881368663515168

0.9881368663515168

In [4]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

sqrt_penalty_matrix = np.eye(2)
penalty = np.array([0, 1E10])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

array([4.98907136, 5.01028281])

array([7.49421271e+00, 1.25257067e-07])

True

array([[ 0.00203735, -0.00203735],
       [-0.00203735,  0.00407471]])

array([[7.29967202e-03, 7.29967230e-10],
       [7.29967230e-10, 9.12459048e-17]])

2858.3793472967886

4826.705984835686

1.018676548720427

7.299672022606387

In [5]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones_like(response)

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

array([-4.38202663])

array([-4.38202663])

True

array([[0.04]])

array([[0.04]])

271.1013317336941

271.1013317336942

1.0

1.0

In [6]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

array([-4.19970508, -0.76214005])

array([-4.19970508, -0.76214005])

True

array([[ 0.06666661, -0.06666661],
       [-0.06666661,  0.20952375]])

array([[ 0.06666667, -0.06666667],
       [-0.06666667,  0.20952381]])

243.45698415537322

243.45698415537322

1.0

1.0

In [7]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()

penalty = np.array([0, 1E3])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

array([-4.7105307 ,  0.44183275])

array([-4.46665187e+00,  2.48570719e-03])

True

array([[ 0.11111111, -0.11111111],
       [-0.11111111,  0.18253966]])

array([[4.34562370e-02, 1.00938521e-03],
       [1.00938521e-03, 2.91329351e-05]])

254.31309521189922

253.40782043347073

1.0

1.0

In [8]:
def simulate_time(n_samples, sampling_frequency):
    return np.arange(n_samples) / sampling_frequency


def simulate_linear_distance(time, track_height, running_speed=10):
    half_height = (track_height / 2)
    return (half_height * np.sin(2 * np.pi * time / running_speed - np.pi / 2)
            + half_height)

def simulate_poisson_spikes(rate, sampling_frequency):
    return 1.0 * (np.random.poisson(rate / sampling_frequency) > 0)


def create_place_field(
    place_field_mean, linear_distance, sampling_frequency, is_condition=None,
        place_field_std_deviation=12.5, max_firing_rate=20,
        baseline_firing_rate=0.5):
    if is_condition is None:
        is_condition = np.ones_like(linear_distance, dtype=bool)
    field_firing_rate = scipy.stats.norm(
        place_field_mean, place_field_std_deviation).pdf(linear_distance)
    field_firing_rate /= field_firing_rate.max()
    field_firing_rate[~is_condition] = 0
    return baseline_firing_rate + max_firing_rate * field_firing_rate

In [9]:
from patsy import build_design_matrices, dmatrices, dmatrix

track_height = 170
n_samples = sampling_frequency * 65

time = simulate_time(n_samples, sampling_frequency)
linear_distance = simulate_linear_distance(
    time, track_height)

place_fields = create_place_field(
    100, linear_distance, sampling_frequency)
spikes = simulate_poisson_spikes(place_fields, sampling_frequency).T

knot_spacing = 15

min_distance, max_distance = (linear_distance.min(),
                              linear_distance.max())
n_steps = (max_distance - min_distance) // knot_spacing
position_knots = min_distance + np.arange(1, n_steps) * knot_spacing
formula = ('is_spike ~ 1 + cr(linear_distance, knots=position_knots,'
           ' constraints="center")')

data = {
    'is_spike': spikes,
    'linear_distance': linear_distance
}
response, design_matrix = dmatrices(formula, data)


In [10]:
%%timeit

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response.squeeze(), family=families.Poisson(), penalty=penalty)

The slowest run took 5.02 times longer than the fastest. This could mean that an intermediate result is being cached.
257 ms ± 176 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%%timeit

model = GLM(response, design_matrix, family=families.Poisson())

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0
fit = model.fit_regularized(alpha=penalty, L1_wt=0,
                            maxiter=25)

3.57 s ± 1.57 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
