In [1]:
%matplotlib inline
#%qtconsole

In [2]:
import numpy as np
import scipy.stats
from statsmodels.api import GLM, families
from regularized_glm.core import penalized_IRLS

n_samples = 1000
response = scipy.stats.norm(loc=5).rvs(n_samples)
design_matrix = np.ones_like(response)

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/miniconda3/envs/regularized_glm/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([5.0247407])

array([[5.0247407]])

True

array([[0.00099385]])

array([[0.00099385]])

2832.7075934018435

array([2832.7075934])

0.9938500163703105

0.9938500163703105

In [3]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([4.93176035, 5.00053377])

array([[4.93176035],
       [5.00053377]])

True

array([[ 0.00213785, -0.00213785],
       [-0.00213785,  0.00427569]])

array([[ 0.00213785, -0.00213785],
       [-0.00213785,  0.00427569]])

2906.5266433307684

array([2906.52664333])

1.0689229787049015

1.0689229787049015

In [4]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

sqrt_penalty_matrix = np.eye(2)
penalty = np.array([0, 1E10])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([4.96101129, 5.03855196])

array([[7.48028721e+00],
       [1.25963796e-07]])

True

array([[ 0.0019879, -0.0019879],
       [-0.0019879,  0.0039758]])

array([[7.34605812e-03, 7.34605840e-10],
       [7.34605840e-10, 9.18257311e-17]])

2833.8054977544202

array([4833.04042572])

0.9939488166210841

7.34605812340447

In [5]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones_like(response)

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.34280592])

array([[-4.34280592]])

True

array([[0.03846154]])

array([[0.03846154]])

281.21220228019104

281.21220228019115

1.0

1.0

In [6]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.19970508, -0.06899287])

array([[-4.19970508],
       [-0.06899287]])

True

array([[ 0.06666667, -0.06666667],
       [-0.06666667,  0.13809524]])

array([[ 0.06666667, -0.06666667],
       [-0.06666667,  0.13809524]])

307.51469491867056

307.51469491867033

1.0

1.0

In [7]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()

penalty = np.array([0, 1E3])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.50986001, -0.31845373])

array([[-4.65571730e+00],
       [-1.49290869e-03]])

True

array([[ 0.09090903, -0.09090903],
       [-0.09090903,  0.21590903]])

array([[5.26135144e-02, 1.00605743e-03],
       [1.00605743e-03, 2.39442898e-05]])

218.46993993287964

216.95059919799294

1.0

1.0

In [8]:
def simulate_time(n_samples, sampling_frequency):
    return np.arange(n_samples) / sampling_frequency


def simulate_linear_distance(time, track_height, running_speed=10):
    half_height = (track_height / 2)
    return (half_height * np.sin(2 * np.pi * time / running_speed - np.pi / 2)
            + half_height)

def simulate_poisson_spikes(rate, sampling_frequency):
    return 1.0 * (np.random.poisson(rate / sampling_frequency) > 0)


def create_place_field(
    place_field_mean, linear_distance, sampling_frequency, is_condition=None,
        place_field_std_deviation=12.5, max_firing_rate=20,
        baseline_firing_rate=0.5):
    if is_condition is None:
        is_condition = np.ones_like(linear_distance, dtype=bool)
    field_firing_rate = scipy.stats.norm(
        place_field_mean, place_field_std_deviation).pdf(linear_distance)
    field_firing_rate /= field_firing_rate.max()
    field_firing_rate[~is_condition] = 0
    return baseline_firing_rate + max_firing_rate * field_firing_rate

In [9]:
from patsy import build_design_matrices, dmatrices, dmatrix

track_height = 170
n_samples = sampling_frequency * 65

time = simulate_time(n_samples, sampling_frequency)
linear_distance = simulate_linear_distance(
    time, track_height)

place_fields = create_place_field(
    100, linear_distance, sampling_frequency)
spikes = simulate_poisson_spikes(place_fields, sampling_frequency).T

knot_spacing = 15

min_distance, max_distance = (linear_distance.min(),
                              linear_distance.max())
n_steps = (max_distance - min_distance) // knot_spacing
position_knots = min_distance + np.arange(1, n_steps) * knot_spacing
formula = ('is_spike ~ 1 + cr(linear_distance, knots=position_knots,'
           ' constraints="center")')

data = {
    'is_spike': spikes,
    'linear_distance': linear_distance
}
response, design_matrix = dmatrices(formula, data)


In [10]:
%%timeit

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response.squeeze(), family=families.Poisson(), penalty=penalty)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:89: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


181 ms ± 54.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%%timeit

model = GLM(response, design_matrix, family=families.Poisson())

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0
fit = model.fit_regularized(alpha=penalty, L1_wt=0,
                            maxiter=25)

2.57 s ± 300 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
