In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
#%qtconsole

In [2]:
import numpy as np
import scipy.stats
from statsmodels.api import GLM, families
from regularized_glm.core import penalized_IRLS

n_samples = 1000
response = scipy.stats.norm(loc=5).rvs(n_samples)
design_matrix = np.ones_like(response)

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/miniconda3/envs/regularized_glm/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([5.03303775])

array([[5.03303775]])

True

array([[0.00097491]])

array([[0.00097491]])

2813.4661404523454

array([2813.46614045])

0.9749097019835102

0.9749097019835102

In [3]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(design_matrix, response)


display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([4.94690843, 5.06697579])

array([[4.94690843],
       [5.06697579]])

True

array([[ 0.00197756, -0.00197756],
       [-0.00197756,  0.00395512]])

array([[ 0.00197756, -0.00197756],
       [-0.00197756,  0.00395512]])

2828.5907319567946

array([2828.59073196])

0.988779097480203

0.9887790974802029

In [4]:
n_samples = 1000
response = np.concatenate(
    (scipy.stats.norm(loc=5).rvs(n_samples // 2),
     scipy.stats.norm(loc=10).rvs(n_samples // 2)))
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

statsmodels_fit = GLM(response, design_matrix).fit()

sqrt_penalty_matrix = np.eye(2)
penalty = np.array([0, 1E10])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([5.03735361, 4.97927711])

array([[7.52699210e+00],
       [1.24481925e-07]])

True

array([[ 0.00196334, -0.00196334],
       [-0.00196334,  0.00392667]])

array([[7.18518926e-03, 7.18518953e-10],
       [7.18518953e-10, 8.98148702e-17]])

2821.3725333454327

array([4810.89842621])

0.9816675905836137

7.185189259554209

In [5]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones_like(response)

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.26869795])

array([[-4.26869795]])

True

array([[0.03571429]])

array([[0.03571429]])

297.04708516454525

297.04708516454514

1.0

1.0

In [6]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()
(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.34280592, -0.08004271])

array([[-4.34280592],
       [-0.08004271]])

True

array([[ 0.07692307, -0.07692307],
       [-0.07692307,  0.1602564 ]])

array([[ 0.07692308, -0.07692308],
       [-0.07692308,  0.16025641]])

273.0613210601948

273.0613210601949

1.0

1.0

In [7]:
n_samples = 2000
rate = np.ones((n_samples,)) * 12
sampling_frequency = 1000
response = np.random.poisson(rate / sampling_frequency)
design_matrix = np.ones((n_samples, 2))
design_matrix[:n_samples // 2, 1] = 0

fam = families.Poisson()
statsmodels_fit = GLM(response, design_matrix, family=fam).fit()

penalty = np.array([0, 1E3])

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=fam, penalty=penalty)

display(statsmodels_fit.params)
display(coefficients, is_converged)

display(statsmodels_fit.cov_params())
display(coefficient_covariance)

display(statsmodels_fit.aic)
display(aic)

display(statsmodels_fit.scale)
display(scale)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


array([-4.60517019,  0.26236426])

array([[-4.46615423e+00],
       [ 1.49142431e-03]])

True

array([[ 0.1       , -0.1       ],
       [-0.1       ,  0.17692306]])

array([[4.34562586e-02, 1.00889038e-03],
       [1.00889038e-03, 2.91099443e-05]])

255.01635767929736

253.41575196997354

1.0

1.0

In [8]:
def simulate_time(n_samples, sampling_frequency):
    return np.arange(n_samples) / sampling_frequency


def simulate_linear_distance(time, track_height, running_speed=10):
    half_height = (track_height / 2)
    return (half_height * np.sin(2 * np.pi * time / running_speed - np.pi / 2)
            + half_height)

def simulate_poisson_spikes(rate, sampling_frequency):
    return 1.0 * (np.random.poisson(rate / sampling_frequency) > 0)


def create_place_field(
    place_field_mean, linear_distance, sampling_frequency, is_condition=None,
        place_field_std_deviation=12.5, max_firing_rate=20,
        baseline_firing_rate=0.5):
    if is_condition is None:
        is_condition = np.ones_like(linear_distance, dtype=bool)
    field_firing_rate = scipy.stats.norm(
        place_field_mean, place_field_std_deviation).pdf(linear_distance)
    field_firing_rate /= field_firing_rate.max()
    field_firing_rate[~is_condition] = 0
    return baseline_firing_rate + max_firing_rate * field_firing_rate

In [9]:
from patsy import build_design_matrices, dmatrices, dmatrix

track_height = 170
n_samples = sampling_frequency * 65

time = simulate_time(n_samples, sampling_frequency)
linear_distance = simulate_linear_distance(
    time, track_height)

place_fields = create_place_field(
    100, linear_distance, sampling_frequency)
spikes = simulate_poisson_spikes(place_fields, sampling_frequency).T

knot_spacing = 15

min_distance, max_distance = (linear_distance.min(),
                              linear_distance.max())
n_steps = (max_distance - min_distance) // knot_spacing
position_knots = min_distance + np.arange(1, n_steps) * knot_spacing
formula = ('is_spike ~ 1 + cr(linear_distance, knots=position_knots,'
           ' constraints="center")')

data = {
    'is_spike': spikes,
    'linear_distance': linear_distance
}
response, design_matrix = dmatrices(formula, data)


In [10]:
%%timeit

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response, family=families.Poisson(), penalty=penalty)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]


120 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%%timeit

model = GLM(response, design_matrix, family=families.Poisson())

penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0
fit = model.fit_regularized(alpha=penalty, L1_wt=0,
                            maxiter=25)

2.22 s ± 171 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
penalty = np.ones((design_matrix.shape[1],)) * 1E1
penalty[0] = 0.0

(coefficients, is_converged, coefficient_covariance, aic, deviance,
 effective_degrees_of_freedom, scale) = penalized_IRLS(
    design_matrix, response * 0.0, family=families.Poisson(), penalty=penalty)

/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:81: RuntimeWarning: divide by zero encountered in true_divide
  * link_derivative ** 2)
/Users/edeno/Documents/GitHub/regularized_glm/regularized_glm/core.py:90: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  full_response * full_weights)[0]
/Users/edeno/miniconda3/envs/regularized_glm/lib/python3.6/site-packages/statsmodels/genmod/families/family.py:371: RuntimeWarning: invalid value encountered in true_divide
  endog_mu = self._clean(endog / mu)
/Users/edeno/miniconda3/envs/regularized_glm/lib/python3.6/site-packages/statsmodels/genmod/families/family.py:404: RuntimeWarning: divide by zero encountered in log
  loglike = np.sum(freq_weights * (endog * np.log(mu) - mu -
/Users/edeno/m